language: java

git:
  depth: false

addons:
  sonarcloud:
    organization: "ghjansen-github"
    token:
      secure: "NzI/v1AYNAkGGIJVkHC48X5jiMam9dv3WlP/ua7DwNhd7snAMVBpwXzEHCKqAnOXXom/rQmw50dvjo54MRkHx3syPLB7ztB7wbyQr7IHspkvuOZLv0nHDV5d20/Rwi2+phW6TIojeh5pL7ydOyRTI9TP5zyCQ52soDCV7+XbzGv7/m20aS/5P8Jvdlx8qDar86MemMKIS+ycEuptMxi/1HNaeOWD5izyoyfDV0251dOOG59MD5sOL6GXZQbp1zXi1Q6T9ZAbuLo38elwCoKahPKrh4TABBQ2P0aKs2/lvJSbWwNGGIYmIEBr7OMG1T0Lw5tLWk9GGP4Us3tCHmwvDWz94eRO1lvYIxYaW+slZw6dFldXJ45TUIFrUu/UPt75PBX9k3Kgxju8nKH4ArtozGKcdySWAUfuViM3ce3OQjGVsweBOiP2o/3i9XvXZmfFlQOj69nnQxJ7EBc5k9Mqjod1hd++B3s3YAzoSjJSdjimziuKKfSTyTyxpzlHG/HBhtGCTplcerXUMtzM2eiIcYg2/+ja4LttnyGhv1PoHst2VG0vpPBPx+bKn0E5L3pF9ltFZrBkt/GE637KR/S1FtkQiUkUjGNAzaVacDsxfhD7Qz+o/SHBfd5I/E19ENx9neop925M1hfBUfPOwL314TaDYOqjmtoGANIJMPRSl58="

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ghjansen-github_cas